### ISSUE TITLE
Benchmarking script fails with unused matrices

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/gotoh2#11]
Encountered this when running through the integrase sequences in `IN.txt` for benchmark testing. 
This exception arose with the sequence at index `26` (here I've hard-coded it for testing):
```
Traceback (most recent call last):
  File "benchmark.py", line 16, in <module>
    g2.align(ref, seqs[26])
  File "/usr/local/lib/python2.7/dist-packages/gotoh2-0.1-py2.7-linux-x86_64.egg/gotoh2/aligner.py", line 73, in align
    self.matrix
RuntimeError: Traceback failed, try local alignment
```
This usually means that the traceback failed (returning a `NULL` value as alignment score) but this routine doesn't print the usual debugging statement.  I've added a couple of print statements and found that the cost and bits matrices haven't been modified from their initial values.

**Comment by ArtPoon** [comment]
It's an empty string :man_facepalming:
