### ISSUE TITLE
Aligner failed on an HIV RT sequence

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/gotoh2#15]
Accession number is AY812749
```
Traceback (most recent call last):
  File "script.py", line 104, in <module>
    # re-align the protein sequences to prevent gaps from breaking codons
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gotoh2-0.1-py3.5-macosx-10.12-x86_64.egg/gotoh2.py", line 84, in align
    self.matrix
RuntimeError: Traceback failed, try local alignment
```

**Comment by ArtPoon** [comment]
Protein alignment doesn't work.  The following test:
```python
    def test_issue15(self):
        ref = 'ERM'
        query = 'ERM'
        self.g2.is_global = False
        self.g2.set_model('EmpHIV25')
        self.g2.gap_open_penalty=40
        self.g2.gap_extend_penalty=10
        result = self.g2.align(ref, query)
        print(result)
```
yields
```python
('--ERM', 'ERM--', 10)
```
Is something wrong with the scoring matrix?

**Comment by ArtPoon** [comment]
Geh - had scores inverted for some reason.
