### ISSUE TITLE
Problems installing on Langley (Ubuntu 16.04.6 LTS)

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/gotoh2#18]
```
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.5/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing top-level names to gotoh2.egg-info/top_level.txt
writing gotoh2.egg-info/PKG-INFO
writing dependency_links to gotoh2.egg-info/dependency_links.txt
reading manifest file 'gotoh2.egg-info/SOURCES.txt'
writing manifest file 'gotoh2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
failed to import Cython: /usr/local/lib/python3.5/dist-packages/Cython/Compiler/Scanning.so: undefined symbol: _Py_ZeroStruct
error: Cython does not appear to be installed
```

**Comment by ArtPoon** [comment]
Interesting, this installation worked with Python 2 on this system.  
Langley is running Python 3.5.2 and Python 2.7.12
Kestrel is running the same version of Ubuntu and the same versions of Python, and I was able to install gotoh2 on this system without any problems.
Something seems to be broken on Langley.

**Comment by ArtPoon** [comment]
Also Cython is not a dependency of gotoh2, so I have no idea why the installer is invoking it on Langley.

**Comment by ArtPoon** [comment]
pip3 was broken.  Fixed:
```console
art@Langley:/home/covid/gotoh2-src$ pip3
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==9.0.1' distribution was not found and is required by the application
art@Langley:/home/covid/gotoh2-src$ sudo easy_install3 --upgrade pip
Searching for pip
Reading https://pypi.python.org/simple/pip/
Best match: pip 20.2b1
Downloading https://files.pythonhosted.org/packages/77/3e/6a1fd8e08a06e3e0f54182c7c937bba3f4e9cf1b26f54946d3915021ea2e/pip-20.2b1.tar.gz#sha256=dbf65ecb1c30d35d72f5fda052fcd2f1ea9aca8eaf03d930846d990f51d3f6f6
Processing pip-20.2b1.tar.gz
...

Installed /usr/local/lib/python3.5/dist-packages/pip-20.2b1-py3.5.egg
Processing dependencies for pip
Finished processing dependencies for pip
art@Langley:/home/covid/gotoh2-src$ pip3

Usage:   
  pip3 <command> [options]
```

Next I updated Cython:
```console
art@Langley:/home/covid/gotoh2-src$ pip3 search cython
Cython (0.29.19)                       - The Cython compiler for writing C
                                         extensions for the Python language.
  INSTALLED: 0.29.15
  LATEST:    0.29.19
...
art@Langley:/home/covid/gotoh2-src$ pip3 install --upgrade Cython
Defaulting to user installation because normal site-packages is not writeable
Collecting Cython
  Downloading Cython-0.29.19-cp35-cp35m-manylinux1_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 3.2 MB/s 
Installing collected packages: Cython
Successfully installed Cython-0.29.19
```

`gotoh2` now installs OK:
```console
art@Langley:/home/covid/gotoh2-src$ sudo python3 setup.py install
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.5/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing gotoh2.egg-info/PKG-INFO
writing dependency_links to gotoh2.egg-info/dependency_links.txt
writing top-level names to gotoh2.egg-info/top_level.txt
reading manifest file 'gotoh2.egg-info/SOURCES.txt'
writing manifest file 'gotoh2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building '_gotoh2' extension
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c src/_gotoh2.c -o build/temp.linux-x86_64-3.5/src/_gotoh2.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/src/_gotoh2.o -o build/lib.linux-x86_64-3.5/_gotoh2.cpython-35m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.5/_gotoh2.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.5/gotoh2.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.5/gotoh2_utils.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/gotoh2.py to gotoh2.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gotoh2_utils.py to gotoh2_utils.cpython-35.pyc
creating stub loader for _gotoh2.cpython-35m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/_gotoh2.py to _gotoh2.cpython-35.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/models
copying models/HYPHY_NUC.csv -> build/bdist.linux-x86_64/egg/models/
copying models/NWALIGN.csv -> build/bdist.linux-x86_64/egg/models/
copying models/Biopp.csv -> build/bdist.linux-x86_64/egg/models/
copying models/EmpHIV25.csv -> build/bdist.linux-x86_64/egg/models/
copying models/BLOSUM62.csv -> build/bdist.linux-x86_64/egg/models/
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying gotoh2.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gotoh2.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gotoh2.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gotoh2.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gotoh2.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/gotoh2-0.1-py3.5-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing gotoh2-0.1-py3.5-linux-x86_64.egg
creating /usr/local/lib/python3.5/dist-packages/gotoh2-0.1-py3.5-linux-x86_64.egg
Extracting gotoh2-0.1-py3.5-linux-x86_64.egg to /usr/local/lib/python3.5/dist-packages
Adding gotoh2 0.1 to easy-install.pth file

Installed /usr/local/lib/python3.5/dist-packages/gotoh2-0.1-py3.5-linux-x86_64.egg
Processing dependencies for gotoh2==0.1
Finished processing dependencies for gotoh2==0.1
```
