### ISSUE TITLE
Can't load module from package root

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/gotoh2#4]
If I launch the Python interpreter from `~/git/gotoh2`, I get the following result:
```
>>> from gotoh2 import aligner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gotoh2/aligner.py", line 1, in <module>
    import Cgotoh2
ImportError: No module named Cgotoh2
```

However, the test script works fine, and if I launch the interpreter elsewhere things seem to be fine.
I must be doing something dumb with the setup script...

**Comment by ArtPoon** [comment]
I think this is caused by having a subdirectory named `gotoh2`. Need to look into how modules are supposed to be structured...

**Comment by ArtPoon** [comment]
Still running into problems loading module, now on Ubuntu 16.04 from ~~anywhere in file system~~ parent directory `~/git` with different error message.
